### ISSUE TITLE
Generating masks for CLEVR dataset

### ISSUE THREAD

**Issue by Tom-Lotze** [deepmind/multi_object_datasets#7]
Hi, I am trying to obtain masks for a self generated CLEVR dataset (with colored backgrounds). Would it be possible to share the code used for obtaining the masks for CLEVR?

Thanks!

**Comment by rishabhkabra** [comment]
Hi Tom-Lotze, I can offer some hints on how to go about it. The original code has a `render_shadeless` function that generates a unique RGB value per object. When the shadeless scene is rendered, it basically looks like a mask (with randomly sampled colors per object). 

So all you need to do is tweak that function a bit. Instead of sampling RGB randomly per object, you could assign one of the three channels based on the object's ID/number.

Hope this helps,
Rishabh
